### ISSUE TITLE
Error : read ECONNRESET

### ISSUE THREAD

**Issue by yjajkiew** [hinzundcode/adaptjs#1]
Hello,

I just discovered your nodejs module and want to give it a try, as it would be useful for some personal projects, but I can't seem to make it work !

I installed adapt as described in mycroft's documentation and can make it work with python and CLI. Then I took your nodejs example, installed your npm module, and I get this error when I try to run it : 

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:896:11)
    at Pipe.onread (net.js:556:26)
```

It seems the error appears because of the lines :

```
.then(intents => { console.log(intents); engine.stop(); })
.catch(error => { console.log(error); engine.stop(); });
```

**Comment by hinzundcode** [comment]
Thanks for your bug report. I added more debug outputs, you can enable them like this:

```
$ DEBUG=* node examples/simple.js
```

Can you send me the output? Which python version and wich operating system do you use?

**Comment by yjajkiew** [comment]
Thank you very much for you help.

I discovered something about the problem : "node examples/simple.js" works perfectly in the end, but the original issue I posted happens with the sudo command : "sudo node examples/simple.js".

With the sudo command and your debug there's no change about the original output I wrote you.

I use the sudo command to launch my nodejs application in order to use the port 80 for instance so that's how I found out about this issue.

I'm using Python 2.7.9 on Raspbian 8 Jessie (Linux raspberrypi 4.1.18-v7+)

**Comment by hinzundcode** [comment]
Did you start it with `$ sudo DEBUG=* node examples/simple.js`? There should be more output.

**Comment by hinzundcode** [comment]
Did you start it with `$ sudo DEBUG=* node examples/simple.js`? There should be more output.

**Comment by yjajkiew** [comment]
The exact output of this command is :

```
adaptjs worker spawned +0ms
Traceback (most recent call last):
  File "/home/pi/test/node_modules/adaptjs/src/worker.py", line 3, in <module>
    from adapt.intent import IntentBuilder
ImportError: No module named adapt.intent
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:896:11)
    at Pipe.onread (net.js:556:26)
```

It works perfectly without the sudo though. 

I am not a python expert but it seems that the problem comes from mycroft-adapt which doesn't like the sudo. 

As recommanded by mycroft I'm using python via virtualenv, which doesn't really like sudo ? I found this post on stackoverflow (http://askubuntu.com/questions/234758/how-to-use-a-python-virtualenv-with-sudo) which states :

> "The issue is almost certainly that when you run sudo, the virtualenv environment variables, aliases, functions, etc aren't being carried over."

The problem is not from your program ;-)

**Comment by hinzundcode** [comment]
Oh, right, python can't find the adapt module. Maybe it'll work if you install adapt globally, without virtualenv. I'd recommend you not to run your program as root, run it as a normal user under a different port (like 8080) and use an webserver (like nginx) which makes it accessible over port 80.

**Comment by yjajkiew** [comment]
Yes, I agree a reverse proxy could be the solution.
Thanks for your help and sorry to have bothered you, I'm closing the issue ;-)

**Comment by ajusa** [comment]
Hi,
I am running into this exact issue. I am also running it off a raspberry pi, with NodeJS 7. My error is identical to the one above. Mycroft seems to have installed correctly, as all of the examples run. What should I do?

```
adaptjs worker spawned +0ms
Traceback (most recent call last):
  File "/home/chip/node_modules/adaptjs/src/worker.py", line 3, in <module>
    from adapt.intent import IntentBuilder
ImportError: No module named adapt.intent
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at Pipe.onread (net.js:572:26)

```

**Comment by ajusa** [comment]
Looks like I solved it somehow by uninstalling python and pip, and reinstalling. For some reason my pip version was defaulting to python3, while by default python is python2. I ran the install command with pip2 and that worked. 

Thank you for writing this wrapper!
